# Checks to see if we're in vim or fzf.
# TODO: try unifying on the `-o tty=` form macos/ uses -- upstream
# vim-tmux-navigator ships that variant for both platforms.
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
is_fzf="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?fzf$'"
