[plugin]
prepend_previewers = [
    { mime = "image/*", run = "code" },
    { mime = "video/*", run = "code" },
    { mime = "application/pdf", run = "code" },
]

[opener]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
    { url = "*.{mp4,mkv,webm,avi,mov}", use = "play" },
]
