#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_placement second_child

yabai -m config top_padding 22
yabai -m config bottom_padding 22
yabai -m config left_padding 22
yabai -m config right_padding 22
yabai -m config window_gap 22

yabai -m config mouse_modifier ctrl
# Put the mouse where the focuse window is
# Useful for quicker resizing and moving of windows
yabai -m config mouse_follows_focus on
# Focus changes when I move the mouse
yabai -m config focus_follows_mouse autoraise
# Drop one window on another to get them to swap
yabai -m config mouse_drop_action swap

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
