prSections:
- title: Needs My Review
  filters: is:open review-requested:@me
- title: My Pull Requests
  filters: is:open author:@me
issuesSections:
- title: jsonassert
  filters: is:open repo:kinbiko/jsonassert
- title: mokku
  filters: is:open repo:kinbiko/mokku
- title: bugsnag
  filters: is:open repo:kinbiko/bugsnag
defaults:
  preview:
    open: true
    width: 80
  prsLimit: 20
  issuesLimit: 20
  view: issues
