general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/.config/wallpapers/lockscreen
    color = rgba(1e1e2eff)
    blur_passes = 0
}

label {
    monitor =
    text = $TIME
    font_size = 64
    position = 0, 120
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 48
    position = 0, -180
    halign = center
    valign = center
    rounding = 8
    outline_thickness = 1
    placeholder_text = Password
    fade_on_empty = false
}
