# For a complete introduction, visit the official docs at: https://espanso.org/docs/
matches:
  - trigger: "a\\\\"
    label: "01. Markdown Link"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: "a\\\\"
    label: "02. HTML Link"
    replace: '<a href="{{clipboard}}">$|$</a>'
    vars:
      - name: "clipboard"
        type: "clipboard"

  # LaTeX bindings
  - trigger: "l;l"
    replace: "$$\n$|$\n$$"
  - trigger: "l;frac"
    replace: "\\frac{1}{n}"
  - trigger: "l;sum"
    replace: "\\sum_{i=1}^{n}"

  # Typos
  - trigger: "saerch"
    replace: "search"
    propagate_case: true

  # Dates
  - trigger: "today\\\\"
    replace: "{{current_date}}"
    vars:
      - name: current_date
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "tomorrow\\\\"
    replace: "{{tomorrow}}"
    vars:
      - name: tomorrow
        type: date
        params:
          format: "%Y-%m-%d"
          offset: 86400

  # Memes
  - trigger: "cowsay\\\\"
    replace: "{{cowsay}}"
    vars:
      - name: cowsay
        type: shell
        params:
          cmd: "cowsay 'Moo!'"

  - trigger: "middle\\\\"
    image_path: "$CONFIG/media/middle.gif"

