# For a complete introduction, visit the official docs at: https://espanso.org/docs/
matches:
  - trigger: "a\\\\"
    label: "Markdown Link"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"

  # Furigana (for GitHub / Obsidian)
  - trigger: "fg\\\\"
    replace: "<ruby>$|$<rt></rt></ruby>"

  # Other symbols
  - trigger: "<--"
    replace: "⇽"
    word: true
  - trigger: "-->"
    replace: "⇾"
    word: true
  - trigger: "green\\\\"
    replace: "🟢"
  - trigger: "yellow\\\\"
    replace: "🟡"
  - trigger: "red\\\\"
    replace: "🔴"

  # Typos
  - trigger: "saerch"
    replace: "search"
    propagate_case: true
  - trigger: "pythong"
    replace: "python"
    propagate_case: true
  - trigger: "assocaited"
    replace: "associated"
    propagate_case: true
    word: true
  - trigger: "shiping"
    replace: "shipping"
    propagate_case: true
    word: true
  - trigger: "langauge"
    replace: "language"
    propagate_case: true
    word: true

  # Better communication
  - trigger: "inflammable"
    replace: "flammable"
    word: true

  # Capitalisation of brands (that aren't also parts of a URL)
  - trigger: "latex"
    replace: "LaTeX"
    word: true

  # Dates
  - trigger: "today\\\\"
    replace: "{{current_date}}"
    vars:
      - name: current_date
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "tomorrow\\\\"
    replace: "{{tomorrow}}"
    vars:
      - name: tomorrow
        type: date
        params:
          format: "%Y-%m-%d"
          offset: 86400

  # These are just better words
  - trigger: "dentures"
    replace: "substiteeth"
    word: true
  - trigger: "forecast"
    replace: "prophecy"
    word: true
  - trigger: "jetski"
    replace: "boatercycle"
    word: true
  - trigger: "hemorrhoids"
    replace: "assteroids"
    word: true
  - trigger: "astronomer"
    replace: "skyintist"
    word: true
  - trigger: "step-dad"
    replace: "faux pa"
    word: true
  - trigger: "toothbrush"
    replace: "teethbrush"
    word: true
  - trigger: "butt dial"
    replace: "booty call"
    word: true
  - trigger: "dad bod"
    replace: "father figure"
    word: true
  - trigger: "narwhal"
    replace: "tunacorn"
    word: true
  - trigger: "mailman"
    replace: "mailmale"
    word: true
  - trigger: "american football"
    replace: "hand egg"
    word: true
  - trigger: "veterinarian"
    replace: "dogtor"
    word: true
  - trigger: "murder of crows"
    replace: "cawcawphony"
    word: true
  - trigger: "fire truck"
    replace: "water truck"
    word: true
  - trigger: "machine gun"
    replace: "rooty tooty fast 'n shooty"
    word: true
  - trigger: "airport"
    replace: "plane station"
    word: true

  # Memes
  - trigger: "cowsay\\\\"
    replace: "{{cowsay}}"
    vars:
      - name: cowsay
        type: shell
        params:
          cmd: "cowsay 'Moo!'"

  - trigger: "middle\\\\"
    image_path: "$CONFIG/media/middle.gif"
  - trigger: "hfy\\\\"
    image_path: "$CONFIG/media/hfy.jpeg"
